# Enable C++ support
language: cpp
# Compiler selection
compiler: gcc
# Build steps
install:
  - sudo pip install cpp-coveralls
# Install a recent CMake (unless already installed on OS X)
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r/test
    packages:
      - cmake
      - cmake-data
      - gcc-6
script:
  - mkdir build
  - cd build
  - cmake .. && make AllUnitTests
  - ./UnitTests/AllUnitTests
