os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      osx_image: xcode8.2

# Enable C++ support
language: cpp
# Compiler selection

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - libpthread-stubs0-dev
    - libgl1-mesa-dev
    - libx11-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libglew1.5-dev
    - libjpeg8-dev
    - libsndfile1-dev
    - libopenal-dev
    - libudev-dev

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ./BUILD/SharedUnitTests
  - ./BUILD/ServerUnitTests
  - ./BUILD/ClientUnitTests

notifications:
  slack: r-type2016:mLsIqykIanE3Yt8cHcLetGuv
