# Enable C++ support
language: cpp
# Compiler selection
compiler: gcc
# Build steps
install:
  - sudo pip install cpp-coveralls
script:
  - mkdir build
  - cd build
  - cmake .. && make AllUnitTests
  - ./AllUnitTests
