sudo: required
dist: trusty

# Enable C++ support
language: cpp
# Enable caching
cache: ccache
# Compiler selection
compiler: gcc
# Build steps
install:
  - sudo pip install cpp-coveralls
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - libpthread-stubs0-dev
    - libgl1-mesa-dev
    - libx11-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libglew1.5-dev
    - libjpeg8-dev
    - libsndfile1-dev
    - libopenal-dev
    - libudev-dev
script:
  - mkdir build
  - cd build
  - cmake .. && make AllUnitTests
  - ./UnitTests/AllUnitTests
